<div class="main">
   <div class="inner_bg_img">
        <div class="inner_banner"><img src="<?php echo $this->constant->IMAGEPATH;?>/inner_banner.png" width="977" height="215" /></div>
    </div>
    <div class="inner_container">
    <div class="search_color inner">
    <div class="breadcrumb pt20"><a href="/">Home</a> <span> &rsaquo; Search ATM</span></div>
    <div class="about_container">
        <form style="margin-bottom:50px" id="search_form" method="get" action="<?php echo $this->constant->HOSTPATH."atm/search/";?>">
            <div class="search_bg">
                <h2 class="page-title">Search ATM</h2>
                <div><img src="<?php echo $this->constant->IMAGEPATH;?>/border.png" width="322" height="1" style="margin:5px 0 0 0;width: 395px;" /></div>
                <div class="search_bank1"  id="bankNameHolder">
                    <div class="text">Bank:</div>
                    <div class="select_box">
                        <select id="bank_name" name="bank_name">
                            <option>Select Bank Name</option>
                            <?php
                            if(isset($this->BankNames) && count($this->BankNames) > 0){
                                foreach($this->BankNames as $key=>$value){
                                    echo '<option>'.$value['bank_name'].'</option>';
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="search_bank1" id="stateNameHolder">
                    <div class="text">State :</div>
                    <div class="select_box">
                        <select id="state_name" name="state_name">
                            <option>Select Bank Above First</option>
                        </select>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="search_bank1 mainoptions" id="districtNameHolder">
                    <div class="text">District :</div>
                    <div class="select_box">
                        <select  id="district_name" name="district_name">
                            <option>Select Bank Above First</option>
                        </select>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="search_bank1 mainoptions"  id="cityNameHolder" >
                    <div class="text">City :</div>
                    <div class="select_box">
                        <select  id="city_name" name="city_name">
                            <option>Select Bank Above First</option>
                        </select>
                        <input name="limitPage" type="hidden" value="1"/>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="search_bank1 mainoptions" id="branchNameHolder" style="display:none">
                    <div class="text">Branch:</div>
                    <div class="select_box">
                        <select id="area" name="area">
                            <option>Select Bank Above First</option>
                        </select>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="search_bank1 mainoptions" id="ifscNameHolder" style="display:none">
                    <div class="text">IFSC Code:</div>
                    <div class="select_box">
                        <input type="text" name="ifsc_code"/>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="search_bank1 mainoptions" id="micrNameHolder" style="display:none">
                    <div class="text">MICR Code:</div>
                    <div class="select_box">
                        <input type="text" name="micr_code"/>
                    </div>
                    <div class="clear"></div>
                </div>

                <div style="margin:15px 0 0 108px;"><a id="submit_link" href="javascript:void(0)"><img src="<?php echo $this->constant->IMAGEPATH;?>/search_button.png" width="104" height="31" border="0" /></a></div>
                
             </div>
            
        </form>
        <?php echo $this->partial('bottomadvertise.phtml', 'default', $this); ?>
         </div>
        
    </div>
    <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
    </div>
    
                            <div style="clear: both"></div>
</div>
   
<script type="text/javascript">
    $('#bank_name').change(function(){        
        if($("#bank_name option:selected").text() == 'Select Bank Name'){
            $("select#state_name").html('<option>Select Bank Above First</option>');
            $('select#state_name').effect("highlight", {}, 3000);
            $("select#district_name").html('<option>Select Bank Above First</option>');
            $("select#city_name").html('<option>Select Bank Above First</option>');
        }else{
            $('#submit_link').hide();
            $("select#state_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'atm/index/getstatejsonatm' ?>",{bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].state + '">' + j[i].state + '</option>';
                  }
              }else{
                  options += '<option value="">No Branch Information Available</option>';
              }
              $("select#state_name").html(options);
              $('select#state_name').effect("highlight", {}, 3000);
                $("select#district_name").html('<option>Select State Above First</option>');
                $("select#city_name").html('<option>Select District Above First</option>');
                $('#submit_link').show();
            })
        }
    });

    $('#state_name').change(function(){
        if($("#branch_search").parent().hasClass('active')){
            if($("#state_name option:selected").text() == 'Please Select'){
                $("select#area").html('<option>Select State Above First</option>');
                $('select#area').effect("highlight", {}, 3000);
            }else{
                $('#submit_link').hide();
                 $("select#area").html('<option>Loading...</option>');
                $.getJSON("<?php echo $this->constant->HOSTPATH.'atm/index/getdistrictjsonatm' ?>",{state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
                  var options = '';
                  if(j.length > 0){
                      options += '<option value="">Please Select</option>';
                      for (var i = 0; i < j.length; i++) {
                        options += '<option value="' + j[i].area + '">' + j[i].area + '</option>';
                      }
                  }else{
                      options += '<option value="">No Branch Information Available</option>';
                  }
                  $("select#area").html(options);
                  $('select#area').effect("highlight", {}, 3000);
                  $('#submit_link').show();
                })
            }
        }else{
            if($("#state_name option:selected").text() == 'Please Select'){
                $("select#district_name").html('<option>Select State Above First</option>');
                $('select#district_name').effect("highlight", {}, 3000);
                $("select#city_name").html('<option>Select State Above First</option>');
            }else{
                $('#submit_link').hide();
                $("select#district_name").html('<option>Loading...</option>');
                $.getJSON("<?php echo $this->constant->HOSTPATH.'atm/index/getdistrictjsonatm' ?>",{state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
                  var options = '';
                  if(j.length > 0){
                      options += '<option value="">Please Select</option>';
                      for (var i = 0; i < j.length; i++) {
                        options += '<option value="' + j[i].district + '">' + j[i].district + '</option>';
                      }
                  }else{
                      options += '<option value="">No District Information Available</option>';
                  }
                  $("select#district_name").html(options);
                  $('select#district_name').effect("highlight", {}, 3000);

                    $("select#city_name").html('<option>Select District Above First</option>');
                    $('#submit_link').show();
                })
            }
        }
    });

    $('#district_name').change(function(){
    
        if($("#district_name option:selected").text() == 'Please Select'){
            $("select#city_name").html('<option>Select District Above First</option>');
            $('select#city_name').effect("highlight", {}, 3000);
        }else{
            $('#submit_link').hide();
            $("select#city_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'atm/index/getcityjsonatm' ?>",{district_name: $("#district_name option:selected").text(),state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].city + '">' + j[i].city + '</option>';
                  }
              }else{
                  options += '<option value="">No City Information Available</option>';
              }
              $("select#city_name").html(options);
              $('select#city_name').effect("highlight", {}, 3000);
              $('#submit_link').show();
            })
        }
    });
    $('#submit_link').click(function(){
        $('#search_form').submit();
    });


    function getVal(value)
   {
   	$('#bank_name').val(value);
       $('#search_form').submit();
    }
    
   function getval(value1)
   {
   	$('#state_name').empty();
   	$('#state_name').append('<option>'+value1+'</option>');
       $('#search_form').submit();
    }

    
    
</script>