<div class="main">
    <div class="inner_container">
    <div class="breadcrumb"><a href="/">Home</a> &rsaquo; <a href="/atm">ATM Location</a><span> &rsaquo; <?php echo $this->Records[0]['bank_name']; ?></span></div>
        <div class="about_container">
            <div class="About_Us"><?php $bank = strtolower($this->Records[0]['bank_name']); echo ucwords($bank);  ?> ATM in <?php echo $this->Records[0]['city']; ?> </div>
            <div class="text_about">
                Note:We took utmost care to collect and provide most updated list of  <?php echo $this->Records[0]['bank_name']; ?> ATM's in  <?php echo $this->Records[0]['city']; ?> listed below:
</br>
"If you find any of the information displayed for ATM Location incorrect, please write to us at 
admin@banksofindia.net.
                 
                 <div style="margin-top: 10px;" >
                     <table cellpadding="0" cellspacing="0" border="0" id="result_table" class="result_table">
                         <tr>
                             <th>Bank Name</th>
                             <th>Area</th>
                             <th>City </th>
                             <?php
                             if(isset($this->params['ifsc_code']) && $this->params['ifsc_code'] !=''){
                                 echo '<th>IFSC Code</th>';
                             }
                             ?>
                             <?php
                             if(isset($this->params['micr_code']) && $this->params['micr_code'] !=''){
                                 echo '<th>MICR Code</th>';
                             }
                             ?>
                         </tr>
                         <?php
                         if(count($this->Records) > 0){
                             foreach($this->Records as $key=>$value){
                                 ?>
                                    <tr>
                                         <td><?php echo $value['bank_name']; ?></td>
                                         <td><a  href="<?php echo $this->constant->HOSTPATH.'atm/detail/'?><?php echo $value['id']; ?>_<?php echo str_replace(' ', '-', $value['bank_name']); ?> <?php echo str_replace(' ', '-', $value['area']); ?>-Branch"><?php echo $value['area']; ?></a></td>
                                         <td><?php echo $value['city']; ?></td>
                                         <?php
                                             if(isset($this->params['ifsc_code']) && $this->params['ifsc_code'] !=''){ ?>
                                                 <td><?php echo $value['ifsc_code']; ?></td>
                                             <?php } ?>
                                         <?php
                                             if(isset($this->params['micr_code']) && $this->params['micr_code'] !=''){ ?>
                                                 <td><?php echo $value['micr_code']; ?></td>
                                             <?php } ?>
                                         
                                     </tr>
                                <?php
                             }
                         }
                         ?>
                     </table>
                     <div id="pagingStateContainer">
                         <?php echo $this->pagination;?>
                     </div>
                 </div>
            </div>
            <?php echo $this->partial('bottomadvertise.phtml', 'default', $this); ?>            
        </div>
        <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
        <div class="clear"></div>
    </div>

</div>
 <!-- <form id="search_form" method="get" action="<?php echo $this->constant->HOSTPATH."atm/index/search/";?>">
    <input type="hidden" value="<?php echo $this->params['bank_name']?>" name="bank_name"/>
    <input type="hidden" value="<?php echo $this->params['state_name']?>" name="state_name"/>
    <input type="hidden" value="<?php echo $this->params['district_name']?>" name="district_name"/>
    <input type="hidden" value="<?php echo $this->params['city_name']?>" name="city_name"/>
    <input type="hidden" value="<?php echo $this->params['area']?>" name="area"/>
    <input type="hidden" value="<?php echo $this->params['ifsc_code']?>" name="ifsc_code"/>
    <input type="hidden" value="<?php echo $this->params['micr_code']?>" name="micr_code"/>
    <input type="hidden" value="<?php echo $this->params['limitPage']?>" name="limitPage" id="limitPage"/>
  </form>  -->
<script type="text/javascript">
function setPage(pageNo){
    $('#limitPage').val(pageNo);
    $('#search_form').submit();
}
var ZebraTable = {
	bgcolor: '',
	classname: '',
	stripe: function(el) {
		//if (!$(el)) return;
		var rows = $('#result_table>tr');
		for (var i=1,len=rows.length;i<len;i++) {
			if (i % 2 == 0) rows[i].className = 'alt';
			Event.add(rows[i],'mouseover',function() { ZebraTable.mouseover(this); });
			Event.add(rows[i],'mouseout',function() { ZebraTable.mouseout(this); });
		}
	},
	mouseover: function(row) {
		this.bgcolor = row.style.backgroundColor;
		this.classname = row.className;
		addClassName(row,'over');
	},
	mouseout: function(row) {
		removeClassName(row,'over');
		addClassName(row,this.classname);
		row.style.backgroundColor = this.bgcolor;
	}
}

window.onload = function() {
	ZebraTable.stripe();
}

</script>