<div class="main">
    <div class="inner_container">
    <div class="breadcrumb"><a href="/">Home</a> <span> &rsaquo; <a href="<?php $bank = str_replace(' ', '_', $this->Records['bank_name']); $bank = strtoupper($bank); echo "/".$bank;?>"><?php if(isset($this->Records['bank_name'])){ $bank = strtolower($this->Records['bank_name']); echo ucwords($bank); } ?></a></span><span> &rsaquo; <?php $branch = strtolower($this->Records['branch_name']); echo ucwords($branch) ?> </span></div>
        <div class="about_container">
            <div class="About_Us"><?php if($this->Records !=''){$bank = strtolower($this->Records['bank_name']);echo ucwords($bank).", ".$this->Records['branch_name'];} ?> Branch Detail</div>
            <div class="text_about">
            
            Note:We tried to provide most updated address and contact number details of  <?php echo $this->Records['bank_name']; ?> in <?php echo $this->Records['city']; ?> location.   
					
                 <br/>
                In case you find any discrepancies in the information of <bank name>, <city> please write to us at 

admin@banksofindia.net.
                 <div style="margin-top: 10px;" >
                     <table cellpadding="0" cellspacing="0" border="0" id="result_table" class="result_table" style="margin-bottom: 10px;border:1px solid #95BCE2">
                        <tr>
                             <td class="header">Bank Name</td>
                             <td class="row"><?php echo $this->Records['bank_name']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">Branch Name</td>
                             <td class="row"><?php echo $this->Records['branch_name']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">Address</td>
                             <td class="row"><?php echo $this->Records['address']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">City</td>
                             <td class="row"><?php echo $this->Records['city']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">District</td>
                             <td class="row"><?php echo $this->Records['district']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">State</td>
                             <td class="row"><?php echo $this->Records['state']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">Phone</td>
                             <td class="row"><?php echo $this->Records['phone']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">Fax</td>
                             <td class="row"><?php echo $this->Records['fax']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">Email</td>
                             <td class="row"><?php echo $this->Records['email']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">MICR Code</td>
                             <td class="row"><?php echo $this->Records['micr_code']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">IFSC Code</td>
                             <td class="row"><?php echo $this->Records['ifsc_code']; ?></td>
                        </tr>
                        <tr>
                             <td class="header">Website</td>
                             <td class="row"><?php echo $this->escape($this->Records['website_url']); ?></td>
                        </tr>
                     </table>
                     <div id="pagingStateContainer">
                         <?php echo $this->pagination;?>
                     </div>
                 </div>
            </div>
            <?php echo $this->partial('bottomadvertise.phtml', 'default', $this); ?> 
                       
        </div>
        <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
        <div class="clear"></div>
    </div>

</div>
<form id="search_form" method="get" action="<?php echo $this->constant->HOSTPATH."default/index/search/";?>">
    <input type="hidden" value="<?php echo $this->params['bank_name']?>" name="bank_name"/>
    <input type="hidden" value="<?php echo $this->params['state_name']?>" name="state_name"/>
    <input type="hidden" value="<?php echo $this->params['district_name']?>" name="district_name"/>
    <input type="hidden" value="<?php echo $this->params['city_name']?>" name="city_name"/>
    <input type="hidden" value="<?php echo $this->params['limitPage']?>" name="limitPage" id="limitPage"/>
</form>
<script type="text/javascript">
function setPage(pageNo){
    $('#limitPage').val(pageNo);
    $('#search_form').submit();
}
var ZebraTable = {
	bgcolor: '',
	classname: '',
	stripe: function(el) {
		//if (!$(el)) return;
		var rows = $('#result_table>tr');
		for (var i=1,len=rows.length;i<len;i++) {
			if (i % 2 == 0) rows[i].className = 'alt';
			Event.add(rows[i],'mouseover',function() { ZebraTable.mouseover(this); });
			Event.add(rows[i],'mouseout',function() { ZebraTable.mouseout(this); });
		}
	},
	mouseover: function(row) {
		this.bgcolor = row.style.backgroundColor;
		this.classname = row.className;
		addClassName(row,'over');
	},
	mouseout: function(row) {
		removeClassName(row,'over');
		addClassName(row,this.classname);
		row.style.backgroundColor = this.bgcolor;
	}
}

window.onload = function() {
	ZebraTable.stripe();
}

</script>