<div class="main">
    
     <div class="inner_bg_img">
        <div class="inner_banner"><img src="<?php echo $this->constant->IMAGEPATH;?>/inner_banner.png" width="977" height="215" /></div>
    </div>
    <div style="clear: both"></div>
    <div class="search_color inner">
        <form id="search_form" method="get" action="<?php echo $this->constant->HOSTPATH."search/";?>">
            <div class="search_bg">
                <div class="Search_Bank_text">Search Bank</div>
                <div><img src="images/border.png" width="322" height="1" style="margin:5px 0 0 0;width: 395px;" /></div>
                
                
                      

                <div class="search_bank1 mainoptions" id="ifscNameHolder">
                    <div class="text">IFSC Code:</div>
                    <div class="select_box">
                        <input type="text" name="ifsc_code"/>
                    </div>
                    <div class="clear"></div>
                </div>
               

                <div style="margin:15px 0 0 108px;"><a id="submit_link" href="javascript:void(0)"><img src="<?php echo $this->constant->IMAGEPATH;?>/search_button.png" width="104" height="31" border="0" /></a></div>
            </div>
        </form>
        <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
    </div>
    
                            <div style="clear: both"></div>
    <div class="add_banner">
        <div style="margin-top:25px; width: 976px; height: 122px;"> <?php echo $this->GoogleAddScript['home_add'];?></div>
    </div>
</div>
<script type="text/javascript">
    $('#bank_name').change(function(){        
        if($("#bank_name option:selected").text() == 'Select Bank Name'){
            $("select#state_name").html('<option>Select Bank Above First</option>');
            $('select#state_name').effect("highlight", {}, 3000);
            $("select#district_name").html('<option>Select Bank Above First</option>');
            $("select#city_name").html('<option>Select Bank Above First</option>');
        }else{
            $('#submit_link').hide();
            $("select#state_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getstatejson' ?>",{bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].state + '">' + j[i].state + '</option>';
                  }
              }else{
                  options += '<option value="">No Branch Information Available</option>';
              }
              $("select#state_name").html(options);
              $('select#state_name').effect("highlight", {}, 3000);
                $("select#district_name").html('<option>Select State Above First</option>');
                $("select#city_name").html('<option>Select District Above First</option>');
                $('#submit_link').show();
            })
        }
    });

    $('#state_name').change(function(){
        if($("#branch_search").parent().hasClass('active')){
            if($("#state_name option:selected").text() == 'Please Select'){
                $("select#branch_name").html('<option>Select State Above First</option>');
                $('select#branch_name').effect("highlight", {}, 3000);
            }else{
                $('#submit_link').hide();
                 $("select#branch_name").html('<option>Loading...</option>');
                $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getbranchjson' ?>",{state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
                  var options = '';
                  if(j.length > 0){
                      options += '<option value="">Please Select</option>';
                      for (var i = 0; i < j.length; i++) {
                        options += '<option value="' + j[i].branch_name + '">' + j[i].branch_name + '</option>';
                      }
                  }else{
                      options += '<option value="">No Branch Information Available</option>';
                  }
                  $("select#branch_name").html(options);
                  $('select#branch_name').effect("highlight", {}, 3000);
                  $('#submit_link').show();
                })
            }
        }else{
            if($("#state_name option:selected").text() == 'Please Select'){
                $("select#district_name").html('<option>Select State Above First</option>');
                $('select#district_name').effect("highlight", {}, 3000);
                $("select#city_name").html('<option>Select State Above First</option>');
            }else{
                $('#submit_link').hide();
                $("select#district_name").html('<option>Loading...</option>');
                $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getdistrictjson' ?>",{state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
                  var options = '';
                  if(j.length > 0){
                      options += '<option value="">Please Select</option>';
                      for (var i = 0; i < j.length; i++) {
                        options += '<option value="' + j[i].district + '">' + j[i].district + '</option>';
                      }
                  }else{
                      options += '<option value="">No District Information Available</option>';
                  }
                  $("select#district_name").html(options);
                  $('select#district_name').effect("highlight", {}, 3000);

                    $("select#city_name").html('<option>Select District Above First</option>');
                    $('#submit_link').show();
                })
            }
        }
    });

    $('#district_name').change(function(){
    
        if($("#district_name option:selected").text() == 'Please Select'){
            $("select#city_name").html('<option>Select District Above First</option>');
            $('select#city_name').effect("highlight", {}, 3000);
        }else{
            $('#submit_link').hide();
            $("select#city_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getcityjson' ?>",{district_name: $("#district_name option:selected").text(),state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].city + '">' + j[i].city + '</option>';
                  }
              }else{
                  options += '<option value="">No City Information Available</option>';
              }
              $("select#city_name").html(options);
              $('select#city_name').effect("highlight", {}, 3000);
              $('#submit_link').show();
            })
        }
    });
    $('#submit_link').click(function(){
        $('#search_form').submit();
    });


     function getVal(value)
    {
    	$('#bank_name').val(value);
        $('#search_form').submit();
     }
     
    function getval(value1)
    {
    	$('#state_name').empty();
    	$('#state_name').append('<option>'+value1+'</option>');
        $('#search_form').submit();
     }
  
</script>