<div class="main">
    
     <div class="inner_bg_img">
        <div class="inner_banner"><img src="<?php echo $this->constant->IMAGEPATH;?>/inner_banner.png" height="150" /></div>
    </div>
   <div class="inner_container">
    <div class="search_color inner">
    <div class="breadcrumb pt20"><a href="/">Home</a> <span> &rsaquo; Search IFSC Code</span></div>
    <div class="about_container">
        <form id="search_form" method="get" action="<?php echo $this->constant->HOSTPATH."ifsc/search/";?>">
            <div class="search_bg">
                <h2 class="page-title">Search IFSC Code</h2>
                <div><img src="images/border.png" width="322" height="1" style="margin:5px 0 0 0;width: 395px;" /></div>
                
                
                      
 
              
               
                <div class="search_bank1 mainoptions"  id="cityNameHolder" >
                    <div class="text">IFSC Code :</div>
                    <div class="select_box">
                       <input name="ifsc_code" id="ifsc_code" type="text" />
                        
                    </div>
                    <div class="clear"></div>
                </div>
                
               

                <div style="margin:15px 0 0 108px;"><a id="submit_link" href="javascript:void(0)"><img src="<?php echo $this->constant->IMAGEPATH;?>/search_button.png" width="104" height="31" border="0" /></a></div>
               
            </div>
            
        </form>
        <?php echo $this->partial('bottomadvertise.phtml', 'default', $this); ?>
         </div>
        
    </div>
    <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
    </div>
    
                            <div style="clear: both"></div>
</div>
<script type="text/javascript">
    $('#bank_name').change(function(){        
        if($("#bank_name option:selected").text() == 'Select Bank Name'){
            $("select#state_name").html('<option>Select Bank Above First</option>');
            $('select#state_name').effect("highlight", {}, 3000);
            $("select#district_name").html('<option>Select Bank Above First</option>');
            $("select#city_name").html('<option>Select Bank Above First</option>');
        }else{
            $('#submit_link').hide();
            $("select#state_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getstatejson' ?>",{bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].state + '">' + j[i].state + '</option>';
                  }
              }else{
                  options += '<option value="">No Branch Information Available</option>';
              }
              $("select#state_name").html(options);
              $('select#state_name').effect("highlight", {}, 3000);
                $("select#district_name").html('<option>Select State Above First</option>');
                $("select#city_name").html('<option>Select State Above First</option>');
                $('#submit_link').show();
            })
        }
    });

    

    $('#state_name').change(function(){
    
        if($("#state_name option:selected").text() == 'Please Select'){
            $("select#city_name").html('<option>Select State Above First</option>');
            $('select#city_name').effect("highlight", {}, 3000);
        }else{
            $('#submit_link').hide();
            $("select#city_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getcityjson' ?>",{state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].city + '">' + j[i].city + '</option>';
                  }
              }else{
                  options += '<option value="">No City Information Available</option>';
              }
              $("select#city_name").html(options);
              $('select#city_name').effect("highlight", {}, 3000);
              $('#submit_link').show();
            })
        }
    });
    $('#submit_link').click(function(){
    	var myString = $('#ifsc_code').val();
    	var length = myString.length;
    	if (length != 11)
    	{
        	alert('Please Insert Correct IFSC Code');
    	}
    	else{
    	window.location.href = "/ifsc/"+$('#ifsc_code').val();
    	}
        });


     function getVal(value)
    {
    	$('#bank_name').val(value);
        $('#search_form').submit();
     }
     
    function getval(value1)
    {
    	$('#state_name').empty();
    	$('#state_name').append('<option>'+value1+'</option>');
        $('#search_form').submit();
     }

   
    
  
</script>