<div class="main">
    <div class="inner_bg_img">
        <div class="inner_banner"><img src="<?php echo $this->constant->IMAGEPATH;?>/inner_banner.png" height="150" /></div>
    </div>
    <div class="inner_container">
    <div class="search_color inner">
    <div class="breadcrumb pt20"><a href="/">Home</a> <span> &rsaquo; MICR Code</span></div>
    <div class="about_container">
        <form id="search_form" method="get" action="<?php echo $this->constant->HOSTPATH."micr/search";?>">
            <div class="search_bg internal_form">

                
            	<h2 class="page-title">Search By MICR Code</h2>

                <div><img src="images/border.png" width="322" height="1" style="margin:5px 0 0 0;width: 395px;" /></div>
               
               
               
                <div class="search_bank1 mainoptions"  id="cityNameHolder" >
                    <div class="text">MICR Code :</div>
                    <div class="select_box">
                       <input name="micr_code" id= "micr_code" type="text"/>
                        <input name="limitPage" type="hidden" value="1"/>
                    </div>
                    <div class="clear"></div>
                </div>
                

              <div style="margin:15px 0 0 108px;"><a id="submit_link" href="javascript:void(0)"><img src="<?php echo $this->constant->IMAGEPATH;?>/search_button.png" width="104" height="31" border="0" /></a></div>
              
            </div>
            
        </form>
         <div class="clear"></div>
        <div>
MICR is Magnetic Ink Character Recognition. It facilitates the processing and clearance of cheques and other documents related to banking. The MICR code is located at the bottom of a cheque. MICR Code, also called MICR line, indicates bank account number, bank code, cheque number and other control indicators. All scheduled banks use their MICR Codes in India and get connected on several grounds in order to provide hassle-free banking transactions.

The MICR tells a lot of things about a particular banking operation. It is extremely difficult to process any third party transaction without having a MICR code. Its primary role is to understand all types of financial transactions from one bank to the other.  

The Magnetic Ink Character Recognition code reader allows scan and read the information directly into a data collection device. There is MICR E-13B font. It is ISO1004-1995 certified international standard. A magnetic ink containing iron oxide is used in the printing of MICR Code. 

These days, MICR Code is also being used in other banking applications like credit cards, airline tickets, Sales, promotions, deposit tickets, insurance premium receipts etc. 
        
               
               </div>
        <?php echo $this->partial('bottomadvertise.phtml', 'default', $this); ?>
         </div>
        
    </div>
    <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
    </div>
    
                            <div style="clear: both"></div>
</div>
<script type="text/javascript">
    $('#bank_name').change(function(){        
        if($("#bank_name option:selected").text() == 'Select Bank Name'){
            $("select#state_name").html('<option>Select Bank Above First</option>');
            $('select#state_name').effect("highlight", {}, 3000);
            $("select#district_name").html('<option>Select Bank Above First</option>');
            $("select#city_name").html('<option>Select Bank Above First</option>');
        }else{
            $('#submit_link').hide();
            $("select#state_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getstatejson' ?>",{bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].state + '">' + j[i].state + '</option>';
                  }
              }else{
                  options += '<option value="">No Branch Information Available</option>';
              }
              $("select#state_name").html(options);
              $('select#state_name').effect("highlight", {}, 3000);
                $("select#district_name").html('<option>Select State Above First</option>');
                $("select#city_name").html('<option>Select State Above First</option>');
                $('#submit_link').show();
            })
        }
    });

    

    $('#state_name').change(function(){
    
        if($("#state_name option:selected").text() == 'Please Select'){
            $("select#city_name").html('<option>Select State Above First</option>');
            $('select#city_name').effect("highlight", {}, 3000);
        }else{
            $('#submit_link').hide();
            $("select#city_name").html('<option>Loading...</option>');
            $.getJSON("<?php echo $this->constant->HOSTPATH.'default/index/getcityjson' ?>",{state_name: $("#state_name option:selected").text(),bank_name: $("#bank_name option:selected").text(), ajax: 'true'}, function(j){
              var options = '';
              if(j.length > 0){
                  options += '<option value="">Please Select</option>';
                  for (var i = 0; i < j.length; i++) {
                    options += '<option value="' + j[i].city + '">' + j[i].city + '</option>';
                  }
              }else{
                  options += '<option value="">No City Information Available</option>';
              }
              $("select#city_name").html(options);
              $('select#city_name').effect("highlight", {}, 3000);
              $('#submit_link').show();
            })
        }
    });
    $('#submit_link').click(function(){
    	var myString = $('#micr_code').val();
    	var length = myString.length;
    	if (length != 9)
    	{
        	alert('Please Insert Correct MICR Code');
    	}
    	else{
    	window.location.href = "/micr/"+$('#micr_code').val();
    	}
    });


     function getVal(value)
    {
    	$('#bank_name').val(value);
        $('#search_form').submit();
     }
     
    function getval(value1)
    {
    	$('#state_name').empty();
    	$('#state_name').append('<option>'+value1+'</option>');
        $('#search_form').submit();
     }
  
</script>