
<div class="search-results">
<?php echo $this->render('index/search.ajax.phtml') ?>
</div>

<script language="javascript">


$(function(){

	console.log("Here goes the pagination text");

	dataContainer = $(".search-results");
	
	$(".pagination-control a").live('click',function(){

		dataContainer.html("<img class='loader' src='/images/ajax-loader.gif'>");
		href = $(this).attr('href');
		href = '<?php echo $this->host ?>'+ href 
		pageNum = $(this).html();

        $.get(href, { format: 'html',page:pageNum}, function(data){

            //alert(data);
            dataContainer.html(data);
        }, 'html');

	    return false;	 
	})	
})

</script>


 