<div class="main">
    <div class="inner_container">
     <div class="breadcrumb pt20"><a href="/">Home</a> <span> &rsaquo; <a href="/micr"> MICR Code </a></span><span> &rsaquo; <?php if(isset($this->Records[0]['bank_name'])) {echo $this->Records[0]['bank_name']; }?>  </span></div>
        <div class="about_container">
            <div class="About_Us"><?php if(isset($this->Records[0]['bank_name'])){ $bank = strtolower($this->Records[0]['bank_name']); echo ucwords($bank); } ?></div>
            <div class="text_about">
                 
                 <div style="margin-top: 10px;" >
                     <table cellpadding="0" cellspacing="0" border="0" id="result_table" class="result_table">
                         <tr>
                         
                             <th>Bank Name</th>
                             <th>Branch Name</th>
                             <th>City </th>
                             <th>MICR Code</th>
                         </tr>
                         <?php
                         if(count($this->Records) > 0){
                             foreach($this->Records as $key=>$value){
                                 ?>
                                    <tr>
                                    
                                    
                                         <td><?php echo $value['bank_name']; ?></td>
                                        
                                         <td><a  href="<?php echo $this->constant->HOSTPATH.'MICRdetail/'?><?php echo $value['id']; ?>_<?php $str = str_replace(' ', '-', $value['bank_name']);  ?>_<?php $str = str_replace(' ', '-', $value['branch_name']); echo str_replace('---','-',$str); ?>-Branch<?php if($value['micr_code'] != ''){echo '-'; echo $value['micr_code'];} ?>"><?php echo $value['branch_name'];  ?></a></td>
                                         <td><?php echo $value['city']; ?></td>
                                        
                                                 <td><?php echo $value['micr_code']; ?></td>
                                            
                                         
                                     </tr>
                                <?php
                             }
                         }
                         else{
                         ?>
                         <tr>
                            <td>Sorry no record found</td>
                            <td></td>
                            <td></td>
                            <td></td>
                         </tr>
                          <?php
                             }
                             ?>
                         
                     </table>
                     <div id="pagingStateContainer">
                         <?php echo $this->pagination;?>
                     </div>
                 </div>
            </div>
            <div class="clear"></div>
             <div class="text_about">
                Note:Based on MICR code - <?php if(isset($this->Records[0]['micr_code'])){ echo $this->Records[0]['micr_code']; }?>  provided by you, we tried to provide <?php if(isset($this->Records[0]['bank_name'])){ echo $this->Records[0]['bank_name']; }?>  contact details, address and IFSC code.
               If you find any of the information displayed for <?php if(isset($this->Records[0]['micr_code'])){ echo $this->Records[0]['micr_code'];} ?>  incorrect, please write to us at admin@banksofindia.net.

                 </div>
            
            
            
            <?php echo $this->partial('bottomadvertise.phtml', 'default', $this); ?>            
        </div>
        <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
        <div class="clear"></div>
    </div>

</div>

<form id="search_form_micr" method="get" action="<?php echo $this->constant->HOSTPATH."micr/search";?>">
    
</form>

<script type="text/javascript">
function setPage(pageNo){
    $('#limitPage').val(pageNo);
    $('#search_form_micr').submit();
}
var ZebraTable = {
	bgcolor: '',
	classname: '',
	stripe: function(el) {
		//if (!$(el)) return;
		var rows = $('#result_table>tr');
		for (var i=1,len=rows.length;i<len;i++) {
			if (i % 2 == 0) rows[i].className = 'alt';
			Event.add(rows[i],'mouseover',function() { ZebraTable.mouseover(this); });
			Event.add(rows[i],'mouseout',function() { ZebraTable.mouseout(this); });
		}
	},
	mouseover: function(row) {
		this.bgcolor = row.style.backgroundColor;
		this.classname = row.className;
		addClassName(row,'over');
	},
	mouseout: function(row) {
		removeClassName(row,'over');
		addClassName(row,this.classname);
		row.style.backgroundColor = this.bgcolor;
	}
}

window.onload = function() {
	ZebraTable.stripe();
}

</script>
