<div class="main">
    
     <div class="inner_bg_img">
        <div class="inner_banner"><img src="<?php echo $this->constant->IMAGEPATH;?>/inner_banner.png" height="150" /></div>
    </div>
   <div class="inner_container " style="width:auto; padding-right:220px" >
    <div class="search_color inner">
    <div class="breadcrumb pt20" style="margin-left:62px;margin-bottom:10px"><a href="/">Home</a> <span> &rsaquo; Site Map</span></div>
<!--     
    <div class="sitemap_links" style="margin-left:50px"><ul>
              <li><a href="/">Home</a></li>
              <li>|</li>
              <li><a href="<?php echo $this->constant->HOSTPATH;?>contactus">Contact Us</a></li>
                            <li>|</li>
             <li><a href="<?php echo $this->constant->HOSTPATH;?>aboutus">About Us</a></li>
                            <li>|</li>
              <li><a href="<?php echo $this->constant->HOSTPATH;?>privacypolicy">Privacy Policy</a></li>
                            <li>|</li>
              <li><a href="<?php echo $this->constant->HOSTPATH;?>helpadnfaq">Help & FAQs</a></li>
                            <li>|</li>
             <li><a href="<?php echo $this->constant->HOSTPATH;?>termsandcondition">Terms & Conditions</a></li>
                     
                            
            </ul></div>
 -->            
    <div class="about_container sitemap_page">
   
    
    <div id="banks_names" style="width:920px; margin:auto"> 
     <div class="sitemap_heading">List of Banks in India</div>
    					 <ul id="banks_list">
                            <?php
                            if(isset($this->BankNames) && count($this->BankNames) > 0){
                                foreach($this->BankNames as $key=>$value){
                                    $bankUrl = str_replace(" ","_",strtoupper($value['bank_name']));
                                    $bankvalue = $value['bank_name'];
									echo "<li><a  href='/$bankUrl'>$bankvalue</a></li>";
                                    
                                }
                            }
                            ?>
                            </ul>
    </div>

    
    <div style="clear: both"></div>
    <div id="city_names" style="width:920px; margin-top:10px;"> 
     <div class="sitemap_heading">List of Cities in India</div>
           <?php 
           if(isset($this->States) && count($this->States) > 0){
				foreach($this->States as $key=>$value){
		   ?>
		   		<div class="state_name" ><?php echo $value['state'] . "</div><div class='cities'>"; 

		   		if(isset($value['city']))
		   		{	
		   			$cities	= explode(",", $value['city']);

		   			echo "<ul id='cities_list'>";
		   			foreach($cities as $keycity=>$valuecity){
		   		
						$stateUrl = str_replace(" ","_",strtoupper($value['state']));
						$cityUrl = str_replace(" ","_",strtoupper($valuecity));

						$host = $this->constant->HOSTPATH;
		   				echo "<li><a  href='/$stateUrl/$cityUrl'>$valuecity</a></li>";
		   			
		   			}
		   			echo "</ul>";
		   			
		   		}	
		   		?>
		   		</div>
		   <?php
		   		}
		   } 
		   ?>
    </div>
    
    
    
    
       
        <?php  echo $this->partial('bottomadvertise.phtml', 'default', $this); ?>
         </div>
        
    </div>
    <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
    </div>
    
                            <div style="clear: both"></div>
</div>


<script type="text/javascript">
 
  
     
     </script>
