<div style="font-size: 18px">
<div style="margin:35px" >

<a style="margin-right:20px" href="<?php echo $this->constant->HOSTPATH.'login'?>">login</a>
<a  href="<?php echo $this->constant->HOSTPATH.'logout'?>">logout</a>

</div>

<div>
<ul>
<li><a  href="<?php echo $this->constant->HOSTPATH.'admin/metatag/manage'?>">Manage Meta Tags</a></li>
<li><a  href="<?php echo $this->constant->HOSTPATH.'admin'?>">Manage Adsense Code</a></li>

</ul>

</div>

</div>