<div style="font-size: 18px">
<div style="margin:35px" >

<a style="margin-right:20px" href="<?php echo $this->constant->HOSTPATH.'login'?>">login</a>
<a  href="<?php echo $this->constant->HOSTPATH.'logout'?>">logout</a>

</div>

<div>
<ul>
<li><a  href="<?php echo $this->constant->HOSTPATH.'admin/metatag/manage'?>">Manage Meta TagsValues</a></li>
<li><a  href="<?php echo $this->constant->HOSTPATH.'admin/metatag/'?>">Insert Meta TagsVvalues</a></li>
<li><a  href="<?php echo $this->constant->HOSTPATH.'admin'?>">Insert Google Adds Script</a></li>

</ul>

</div>

</div>