<div class="inner_container">
<div style="font-size: 15px;text-align:right" >
<a  href="<?php echo $this->constant->HOSTPATH.'logout'?>">logout</a> 
</div>

<div style="margin-top: 25px;" >
<ul>
<li><a  href="<?php echo $this->constant->HOSTPATH.'admin/metatag/manage'?>">Manage Meta Tags</a></li>
<li><a  href="<?php echo $this->constant->HOSTPATH.'admin'?>">Manage Adsense Code</a></li>

</ul>

                     </div>
                     </div>