<div class="inner_container">
<div style="margin-top: 10px;" >
                     <table cellpadding="0" cellspacing="0" border="0" id="result_table" class="result_table">
                     <thead>
                         <tr class="result">
                         
                             <th>Page URL</th>
                             <th>Title</th>
                             <th>keywords</th>
                              <th>Description</th>
                              <th>Operation</th>
                             
                         </tr>
                     </thead>
                     <tbody>    
                         <?php
                         if(count($this->Records) > 0){
                             foreach($this->Records as $key=>$value){
                                 ?>
                                    <tr class="result">
                                    
                                    
                                         <td><?php echo $value['page_url']; ?></td>
                                        <td><?php echo $value['title']; ?></td>
                                        <td><?php echo $value['keywords']; ?></td>
                                         <td><?php echo $value['description']; ?></td>
                                         <td><a  href="<?php echo $this->constant->HOSTPATH.'admin/metatag/'?><?php echo $value['id']; ?>">Edit</a> <a  href="<?php echo $this->constant->HOSTPATH.'admin/metatag/deleted/'?><?php echo $value['id']; ?>">Delete</a></td>
                                        
                                     </tr>
                                <?php
                             }
                         }
                         ?>
                        </tbody> 
                     </table>
                     </div>
                     </div>