<div class="inner_container">

<div class="breadcrumb"><a href="/admin/dashboard">Dashboard</a> &rsaquo; <a href="/admin/metatag/manage">Manage Meta Tags</a> <span> &rsaquo; Add/Edit Meta Tag</span></div>

<div style="font-size: 15px;text-align:right" >
<a  href="<?php echo $this->constant->HOSTPATH.'logout'?>">logout</a>
</div>

<div style="margin-top: 25px;" >
<form id="meta_tag_script" method="post" action="<?php echo $this->constant->HOSTPATH."admin/metatag";?>" >
<div>
<div class="meta_tag_text">URL (example /atm, and only / for home page)</div>
<textarea name="page_url" class="meta_tag_input" id="page_url" ><?php if(isset($this->value['id'])){echo $this->value['page_url']; }?></textarea>
</div>
<div>
<div class="meta_tag_text">Title</div>
<textarea name="title" class="meta_tag_input" id="title"></textarea>
</div>
<div>
<div class="meta_tag_text">Keywords</div>
<textarea name="keywords" class="meta_tag_input" id="keywords" ></textarea>
</div>
<div>
<div class="meta_tag_text">Description</div>
<textarea name="description" class="meta_tag_input" id="description" ></textarea>
</div>

<input class="meta_tag_submit" type="submit" value="submit">
<input class="meta_tag_submit" type="button" value="Reset">
<input class="meta_tag_submit" type="button" value="Back">

</form>

                     </div>
                     </div>
                     
<script language="javascript">

	$(function(){

		$("input[value^=Back]").click(function(){
			window.location.href = "/admin/metatag/manage";
			return false;
		});


		$("input[value^=Reset]").click(function(){
			$(".meta_tag_input").val('');			
		});
		
			
	});

</script>                     