<div>
<form id="meta_tag_script" method="post" action="<?php echo $this->constant->HOSTPATH."admin/metatag";?>" >
<div>
<div class="meta_tag_text">URL (example /atm, and only / for home page)</div>
<textarea name="page_url" class="meta_tag_input" id="page_url" ></textarea>
</div>
<div>
<div class="meta_tag_text">Title</div>
<textarea name="title" class="meta_tag_input" id="title"></textarea>
</div>
<div>
<div class="meta_tag_text">Keywords</div>
<textarea name="keywords" class="meta_tag_input" id="keywords" ></textarea>
</div>
<div>
<div class="meta_tag_text">Description</div>
<textarea name="description" class="meta_tag_input" id="description" ></textarea>
</div>

<input class="meta_tag_submit" type="submit" value="submit">

</form>

</div>