<div class="main">
    <div class="inner_bg_img">
        <div class="inner_banner"><img src="<?php echo $this->constant->IMAGEPATH;?>/inner_banner.png" height="150" /></div>
    </div>
    <div class="inner_container">
    <div class="breadcrumb"><a href="/">Home</a> <span> &rsaquo; <?php echo $this->PageHead;?></span></div>
        <div class="about_container">
            <div class="About_Us"><?php echo $this->PageHead;?></div>
            <div class="text_about">
                	We are committed to protect personal information/data of our customers and maintain privacy policy of their personal information which allows us to approach towards handling or dealing with the same. Our Privacy Policy is designed and developed to address the privacy and security of your personal information provided to us. 
                	<br/>
Essentially, any piece of "Personal information" that could be used to distinctively identify a person, contact him/her, or locate an individual, or could be used with information available from other sources to uniquely identify a user. For the purpose of this privacy policy, your confidential data or information has been given due consideration. Your privacy is important to us.
<br/>
The personal information is purely used to analyze trends, study the site and track movement of users to gather broad demographic information for internal use. We have included links on this site for reference. We are not responsible for the privacy policies on these websites. The content of this statement may be altered at any time at our discretion.
<br/>
Users of this site may be permitted to submit comment for publication. You will be deemed to consent to these guidelines, and their terms and conditions, if you choose to post any comments to the site. We, or authorized third parties, reserve the right to refuse to publish, cut, crop or edit your content at our or their sole discretion. We may remove your content from use at any time. We warrant that the content you submit to us is not obscene, menacing, vilifying, deceitful, harassing, misleading, offensive, and invasive of another's privacy.
<br/> 
Banks in India reserves the right to amend or modify this Privacy Policy at any time, if the need arises. We request you to visit our website periodically for up to date information and changes.
            </div>
             <?php echo $this->partial('bottomadvertise.phtml', 'default', $this); ?>        
        </div>
        <?php echo $this->partial('rightadvertise.phtml', 'default', $this); ?>
        <div class="clear"></div>
    </div>

</div>